# Generated by Django 3.2.7 on 2021-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(max_length=200)),
                ('uploaded_By', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
